# Dawn Cluster (Cambridge HPC) Dense Retriever Configuration
# Hardware: Intel Xeon Platinum 8368Q + Intel PVC GPUs
# Partition: pvc9

defaults:
  - encoder: hf_bert
  - datasets: retriever_default
  - ctx_sources: default_sources

indexers:
  flat:
    _target_: dpr.indexer.faiss_indexers.DenseFlatIndexer

  hnsw:
    _target_: dpr.indexer.faiss_indexers.DenseHNSWFlatIndexer

  hnsw_sq:
    _target_: dpr.indexer.faiss_indexers.DenseHNSWSQIndexer

name: dpr_dawn

hydra:
  run:
    dir: outputs/${name}/test

# the name of the queries dataset from the 'datasets' config group
qa_dataset:

# a list of names of the passages datasets from the 'ctx_sources' config group
ctx_datatsets:

# Glob paths to encoded passages (from generate_dense_embeddings tool)
encoded_ctx_files: []

out_file:
# "regex" or "string"
match: string
n_docs: 100

# Dawn cluster has 76 CPUs per node - use more workers
validation_workers: 32

# Batch size for query embeddings - can be larger with ~1TB RAM
batch_size: 256

# Whether to lower case the input text
do_lower_case: True

# The attribute name of encoder to use for queries
encoder_path:

# Path to the FAISS index location
index_path:

kilt_out_file:

# A trained bi-encoder checkpoint file to initialize the model
model_file:

validate_as_tables: False

# RPC settings
rpc_retriever_cfg_file:
rpc_index_id:
use_l2_conversion: False
use_rpc_meta: False
rpc_meta_compressed: False

indexer: flat

# tokens which won't be split by tokenizer
special_tokens:

# Intel XPU distributed config
local_rank: -1
global_loss_buf_sz: 150000

# Use Intel XPU device
device: xpu

distributed_world_size:
distributed_port:
no_cuda: True
n_gpu:

# Intel PVC prefers bf16 over fp16
fp16: False
bf16: True
fp16_opt_level:
