# Dawn Cluster (Cambridge HPC) Embedding Generation Configuration
# Hardware: Intel Xeon Platinum 8368Q + Intel PVC GPUs
# Partition: pvc9

defaults:
  - encoder: hf_bert
  - ctx_sources: default_sources

# A trained bi-encoder checkpoint file to initialize the model
model_file:

# Name of the all-passages resource
ctx_src:

# which (ctx or query) encoder to be used for embedding generation
encoder_type: ctx

# output .tsv file path to write results to
out_file:

# Whether to lower case the input text
do_lower_case: True

# Number (0-based) of data shard to process
shard_id: 0

# Total amount of data shards
num_shards: 1

# Batch size for the passage encoder forward pass
# Dawn cluster has ~1TB RAM and Intel PVC GPUs - can use larger batches
batch_size: 4096

tables_as_passages: False

# tokens which won't be split by tokenizer
special_tokens:

tables_chunk_sz: 100

tables_split_type: type1

name: dpr_dawn

hydra:
  run:
    dir: outputs/${name}/embs_${shard_id}

# Intel XPU settings for Dawn cluster
local_rank: -1
device: xpu
distributed_world_size:
distributed_port:
no_cuda: True
n_gpu:

# Intel PVC prefers bf16 over fp16
fp16: False
bf16: True
fp16_opt_level:
